"""Loads the QR code / NFC tag -> content mapping and resolves actions.

The mapping file (config/mapping.json) is the single source of truth for
"what happens when this code/tag is scanned". It is intentionally a plain
JSON file so it can be edited by hand or generated by a small helper script
without touching any Python code.

The file's modification time is checked on every lookup, so editing
mapping.json while the hub is running takes effect on the next scan — no
restart required.
"""
import json
import logging
import os

from . import config

logger = logging.getLogger(__name__)


class ContentMapper:
    def __init__(self, mapping_file=config.MAPPING_FILE):
        self.mapping_file = mapping_file
        self._mapping = {"qr": {}, "nfc": {}}
        self._mtime = None
        self.reload()

    def reload(self):
        """Re-read the mapping file from disk."""
        try:
            self._mtime = os.path.getmtime(self.mapping_file)
            with open(self.mapping_file, "r", encoding="utf-8") as f:
                self._mapping = json.load(f)
            logger.info(
                "Loaded mapping: %d QR codes, %d NFC tags",
                len(self._mapping.get("qr", {})),
                len(self._mapping.get("nfc", {})),
            )
        except FileNotFoundError:
            logger.warning(
                "Mapping file not found at %s — copy config/mapping.example.json "
                "to config/mapping.json and fill it in.",
                self.mapping_file,
            )
        except json.JSONDecodeError as exc:
            logger.error("mapping.json has invalid JSON: %s", exc)

    def _maybe_reload(self):
        """Reload if mapping.json changed on disk since we last read it."""
        try:
            mtime = os.path.getmtime(self.mapping_file)
        except OSError:
            return
        if mtime != self._mtime:
            logger.info("mapping.json changed on disk — reloading.")
            self.reload()

    def resolve_qr(self, code: str):
        self._maybe_reload()
        return self._mapping.get("qr", {}).get(code)

    def resolve_nfc(self, uid: str):
        self._maybe_reload()
        return self._mapping.get("nfc", {}).get(uid.upper())
