"""Loads the QR code / NFC tag -> content mapping and resolves actions.

The mapping file (config/mapping.json) is the single source of truth for
"what happens when this code/tag is scanned". It is intentionally a plain
JSON file so it can be edited by hand or generated by a small helper script
without touching any Python code.
"""
import json
import logging

from . import config

logger = logging.getLogger(__name__)


class ContentMapper:
    def __init__(self, mapping_file=config.MAPPING_FILE):
        self.mapping_file = mapping_file
        self._mapping = {"qr": {}, "nfc": {}}
        self.reload()

    def reload(self):
        """Re-read the mapping file from disk. Safe to call at any time,
        e.g. after editing mapping.json while the hub is running."""
        try:
            with open(self.mapping_file, "r", encoding="utf-8") as f:
                self._mapping = json.load(f)
            logger.info(
                "Loaded mapping: %d QR codes, %d NFC tags",
                len(self._mapping.get("qr", {})),
                len(self._mapping.get("nfc", {})),
            )
        except FileNotFoundError:
            logger.warning(
                "Mapping file not found at %s — copy config/mapping.example.json "
                "to config/mapping.json and fill it in.",
                self.mapping_file,
            )
        except json.JSONDecodeError as exc:
            logger.error("mapping.json has invalid JSON: %s", exc)

    def resolve_qr(self, code: str):
        return self._mapping.get("qr", {}).get(code)

    def resolve_nfc(self, uid: str):
        return self._mapping.get("nfc", {}).get(uid.upper())
